sudo: required

services:
  - docker

before_install:
  - docker build -t darivo/vida-users-service .

script:
  - docker run darivo/vida-users-service npm test

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push darivo/vida-users-service

deploy: 
  provider: elasticbeakstalk
  region: eu-west-2
  app: vida-users-service
  env: VidaUsersService-env
  bucket_name: elasticbeanstalk-eu-west-2-653100821739
  bucket_path: vida-users-service
  on: 
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY